server:
  port: 8761 # port는 8761
  
 
spring:
  application:
    name: discoveryservice1 # 서비스명 등록
    
eureka:
  client:
    register-with-eureka: false # 디스커버리서버에 등록할 것이냐? 아니오.
    fetch-registry: false # 유레카서버(=디스커버리서버)로부터 다른 인스턴스(서비스)들의 정보를 가져와 갱신할것이냐? 아니오.
    