server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
#          uri: file:D:\\workspace\workspace_boot\usinsaWork\\git-repo
          uri: https://github.com/dsadsaddd1/USINSAaaa.git
  application:
    name: config-service